# Generated by Django 5.1.3 on 2024-12-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/flowers/'),
        ),
    ]
